apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
      app.kubernetes.io/name: hello-world-pictolearn
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007


#kubectl expose deployment hello --port 18080 --name hello-np --type NodePort